// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {indentation, newlines} from "./tokens"
import {trackIndent} from "./tokens.js"
import {jsonHighlighting} from "./highlight"
const spec_Key = {__proto__:null,"---":58, true:68, false:68, null:70, "~":70, "|":80, ">":80, "|-":80, ">-":80, "|+":80, ">+":80, "...":86}
export const parser = LRParser.deserialize({
  version: 14,
  states: "'[O]QYOOOOQW'#C_'#C_ObQYO'#CxQOQYOOOgQYO,59dOoQYO'#CzOOQW'#Cn'#CnOgQYO1G/OOOQW'#Cm'#CmOOQW1G/O1G/OO!VQYO,59fOOQW-E6l-E6lOOQW7+$j7+$jOOQW'#Ca'#CaOOQW'#Cb'#CbOOQW'#Cd'#CdOOQW'#C}'#C}OOQW'#Cf'#CfO!gQYO'#CeO!lQYO'#CeO!qQYO'#CiO!xQYO'#ClOOQW'#C|'#C|O#PQYO1G/QO#UQYO,59PO#UQYO,59PO#ZQ[O'#DVOOQW,59T,59TO#fQYO,59TOOQW,59W,59WO#kQYO,59WOOQW7+$l7+$lO#pOPO'#DTO#uQYO1G.kOOQW1G.k1G.kOtQYO'#CpO#zQ[O,59qOOQW1G.o1G.oOOQW1G.r1G.rO$VOQO,59oOOQW7+$V7+$VOOQW,59[,59[OOQW-E6n-E6nO$[OWO'#CoO$aORO1G/ZOOOP,59Z,59ZOOOP-E6m-E6mOOQW7+$u7+$u",
  stateData: "$k~OkOSiOSPOS~OmPO~OhSO~OSTO{WO~OoYO~OV`Or]Os^Ot_Ou_O~O[dO_eOvbOxaO~PtOthO~OhiO~OZkO~PtO^mO~PtOhoO~OhpO~OzsOZyX^yX~OZuO~O^vO~OfwO~OvxO~OzsOZya^ya~Ot{O~Oh}O~Og!POt{O~Ot~",
  goto: "#fzPPP{P!O!OP!O!U!XPP!UPP!U![!b!h!nPPPPPPP!tP!wP!{#OPPPPP#YP#`RQOX`YdesRfYRcYQXSR[VQVSRZVQ|wR!O|QtjRztRROTUSVRgYQfYSjdeRysQqhRriQldRne",
  nodeNames: "⚠ Comment YamlText DocStart Key Boolean Null Number String MultiLine FoldOp } { Mapping ] [ Sequence DocEnd",
  maxTerm: 43,
  context: trackIndent,
  nodeProps: [
    ["openedBy", 11,"{",14,"["],
    ["closedBy", 12,"}",15,"]"]
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "9r~RnOX#PXY$oY[#P[]$o]p#Ppq$ors%Zst'ktu#Pwz#P{|#P|}'y}!O(b!O!P+Y!P!Q#P!Q!R2h!R![4^![!]6b!]!^#P!c!}6m!}#O8q#O#P8v#P#Q9c#Q#R#P#R#S6m#S#T#P#T#o6m#o#p9h#q#r9m#r~#PP#SUOY#fZ]#f^r#fs#O#f#O#P#}#P~#fP#kUtPOY#fZ]#f^r#fs#O#f#O#P#}#P~#fP$SXtPOY#fYZ#fZ]#f]^#f^r#frs#fs#O#f#O#P#}#P~#f~$tSk~XY$o[]$opq$o#O#P%Q~%TQYZ$o]^$o~%`Uv~OY%rZ]%r^r%rs#O%r#O#P&a#P~%r~%uVOY%rZ]%r^r%rrs&[s#O%r#O#P&a#P~%r~&aOu~~&dXOY%rYZ%rZ]%r]^%r^r%rrs'Ps#O%r#O#P&a#P~%r~'UVu~OY%rZ]%r^r%rrs&[s#O%r#O#P&a#P~%r~'pRP~OY'kZ]'k^~'kR(OUzQOY#fZ]#f^r#fs#O#f#O#P#}#P~#f~(eR!O!P(n!Q!R*i!R![*w~(qR!Q![(z#]#^)t#b#c*]~)PRV~!Q![(z!g!h)Y#X#Y)Y~)]R{|)f}!O)f!Q![)l~)iP!Q![)l~)qPV~!Q![)l~)wP#b#c)z~)}P#Y#Z*Q~*VQV~!g!h)Y#X#Y)Y~*`P#T#U*c~*fP#b#c*Q~*nRV~!O!P(n!g!h)Y#X#Y)Y~*|SV~!O!P(n!Q![*w!g!h)Y#X#Y)Y~+][OY#fZ]#f^r#fs!Q#f!Q![,R![#O#f#O#P#}#P#]#f#]#^/X#^#b#f#b#c1[#c~#f~,Y[V~tPOY#fZ]#f^r#fs!Q#f!Q![,R![!g#f!g!h-O!h#O#f#O#P#}#P#X#f#X#Y-O#Y~#f~-T[tPOY#fZ]#f^r#fs{#f{|-y|}#f}!O-y!O!Q#f!Q![.h![#O#f#O#P#}#P~#f~.OWtPOY#fZ]#f^r#fs!Q#f!Q![.h![#O#f#O#P#}#P~#f~.oWV~tPOY#fZ]#f^r#fs!Q#f!Q![.h![#O#f#O#P#}#P~#f~/^WtPOY#fZ]#f^r#fs#O#f#O#P#}#P#b#f#b#c/v#c~#f~/{WtPOY#fZ]#f^r#fs#O#f#O#P#}#P#Y#f#Y#Z0e#Z~#f~0lYV~tPOY#fZ]#f^r#fs!g#f!g!h-O!h#O#f#O#P#}#P#X#f#X#Y-O#Y~#f~1aWtPOY#fZ]#f^r#fs#O#f#O#P#}#P#T#f#T#U1y#U~#f~2OWtPOY#fZ]#f^r#fs#O#f#O#P#}#P#b#f#b#c0e#c~#f~2m[V~OY#fZ]#f^r#fs!O#f!O!P3c!P!g#f!g!h-O!h#O#f#O#P#}#P#X#f#X#Y-O#Y~#f~3h[tPOY#fZ]#f^r#fs!Q#f!Q![,R![#O#f#O#P#}#P#]#f#]#^/X#^#b#f#b#c1[#c~#f~4c^V~OY#fZ]#f^r#fs!O#f!O!P3c!P!Q#f!Q![5_![!g#f!g!h-O!h#O#f#O#P#}#P#X#f#X#Y-O#Y~#f~5f^V~tPOY#fZ]#f^r#fs!O#f!O!P3c!P!Q#f!Q![5_![!g#f!g!h-O!h#O#f#O#P#}#P#X#f#X#Y-O#Y~#f~6ePpq6h~6mOo~~6r^S~OY#fZ]#f^r#fs!Q#f!Q![7n![!c#f!c!}7n!}#O#f#O#P#}#P#R#f#R#S7n#S#T#f#T#o7n#o~#f~7u^S~tPOY#fZ]#f^r#fs!Q#f!Q![7n![!c#f!c!}7n!}#O#f#O#P#}#P#R#f#R#S7n#S#T#f#T#o7n#o~#f~8vO_~~8yWOY#fYZ$oZ]#f]^$o^r#fs#O#f#O#P#}#P~#f~9hO^~~9mO[~~9rOZ~",
  tokenizers: [indentation, 0, 1, newlines],
  topRules: {"YamlText":[0,2]},
  specialized: [{term: 4, get: value => spec_Key[value] || -1}],
  tokenPrec: 163
})
