// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 22,
  dedent = 23,
  newline = 24,
  newlineEmpty = 25,
  Comment = 1,
  YamlText = 2,
  DocStart = 3,
  Key = 4,
  Boolean = 5,
  Null = 6,
  Number = 7,
  String = 8,
  MultiLine = 9,
  FoldOp = 10,
  Mapping = 13,
  Sequence = 16,
  DocEnd = 17
